### PR TITLE
add context support

### PR DESCRIPTION
**Pull request by charliewolf**
This will allow a user to pass context, either an object or function, that will be used in the template engine.

### CODE REVIEW

**Comment by Pancia** [comment]
Any reason this isn't merged in? I could definitely use this.

**Comment by HenrikJoreteg** [comment]
@Pancia @charliewolf only reason is I haven't had a chance to actually use this and this is not a lib I'm currently using for any of my projects :) Though, I'm happy to add either or both of you to the project if you just take care to follow the style/simplicity of the project and always follow semver when publishing.

**Comment by Pancia** [comment]
I'll be happy to help out.

I've been using this for testing using spacemonkey and I wanted an easier way to have multiple test files but still have only one index.jade. I ended up using query params (?name=$testName), but there might be a better way if I knew more about spacemoney...

**Comment by HenrikJoreteg** [comment]
@Pancia cool, i've added you so you can push to this repo.

**Comment by Pancia** [comment]
Merged in d489cbea1f5946dd3b6828e0dc9feb9575f36f1d

**Pull request closed without merging**
