### PR TITLE
add keepExt flag to retain extension of file

### PR DESCRIPTION
**Pull request by charliewolf**
Hi, for my app I need to be able to render, say, test.html as /test.html rather than just /test so I added a flag to allow this.

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
Hi, @charliewolf sorry this sat so long. I'm going to close it because it's old, but if you're still wanting/needing this, please re-open this issue.

I'll happily add you as a contributor if you'd like. As i mentioned in another thread I'm not actively using this on any projects so I'd love help maintaining it.

**Comment by charliewolf** [comment]
It's still a useful feature in my opinion but at the same time I can't commit to help maintaining it at the moment.

**Comment by HenrikJoreteg** [comment]
Even if you just want to merge/deploy this one thing, that'd be fine :) Basically I'm happy to give access to the repo and npm to anyone who's actively using it. So anyway, lemme know.

**Comment by charliewolf** [comment]
Sure, that's fine then

**Comment by HenrikJoreteg** [comment]
done and npm too.

**Pull request closed without merging**
